# Permalinks
permalink:        pretty

# Setup
url:              http://thereedtreewedding.co.uk

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ""

title:            The Reed Tree Wedding

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  Find all the information you need about the Reed Tree wedding here.

# The tags listed as entries in the sidebar
sidebar_tags:     [jekyll, hyde]

# Fallback image and color if not overwritten for tag or post
image:            /public/img/title.jpg
color:            '#A85641'

author:
  name:           'Toby Jackson'
#  twitter:        warmfusion
#  github:         warmfusion
  photo:          /public/img/toby.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, I'm Toby or [`@warmfusion`](https://www.twitter.com/warmfusion), and I
    helped make this website for Caroline and Rob's big day!

    If you're interested in knowing more, check out [my website](http://warmfusion.co.uk).



collections:
  sections:
    output: false
